config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'
  root to: 'movies#index'
  post 'imports/movie/csv', to: 'movies#import'
  post 'imports/review/csv', to: 'reviews#import'
  resources :movies do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews, dependent: :delete_all
  
    validates :name, :description, presence: true
  
    def calc_average_rating
      reviews.present? ? reviews.average(:stars) : 0.0
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
end

app/models/review_observer.rb
class ReviewObserver < ActiveRecord::Observer
    def after_commit(review)
      movie = review.movie
      movie.update(average_rating: movie.calc_average_rating)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_movie, only: %i[show edit update destroy]
  
    # GET /movies
    def index
      @q = Movie.includes(:reviews).ransack(params[:q])
      @movies = @q.result
    end
  
    # GET /movies/1
    def show; end
  
    # GET /movies/new
    def new
      @movie = Movie.new
    end
  
    # GET /movies/1/edit
    def edit; end
  
    # POST /movies 
    def create
      @movie = Movie.new(movie_params)
  
      respond_to do |format|
        if @movie.save
          format.html { redirect_to movie_url(@movie), notice: 'Movie was successfully created.' }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /movies/1 
    def update
      respond_to do |format|
        if @movie.update(movie_params)
          format.html { redirect_to movie_url(@movie), notice: 'Movie was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /movies/1
    def destroy
      @movie.destroy
  
      respond_to do |format|
        format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      end
    end

    def import
        return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
        unless params[:file].content_type == 'text/csv'
          return redirect_to request.referer,
                             notice: 'Only CSV files allowed'
        end
        ImportMovieCsv.new(params[:file]).call
        redirect_to request.referer, notice: 'Import started async, please refresh your page after some minutes...'
    end
  
    private

  
    def set_movie
      @movie = Movie.find(params[:id])
    end
  
    def movie_params
      params.require(:movie).permit(:name, :description, :year, :director, :actor, :filming_location, :country)
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_movie, only: %i[index show edit update destroy new create]
    before_action :set_review, only: %i[show edit update destroy]
  
    # GET /reviews 
    def index
      @reviews = @movie.reviews
    end
  
    # GET /reviews/1
    def show; end
  
    # GET /reviews/new
    def new
      @review = @movie.reviews.build
    end
  
    # GET /reviews/1/edit
    def edit; end
  
    # POST /reviews
    def create
      @review = @movie.reviews.build(review_params)
  
      respond_to do |format|
        if @review.save
          format.html { redirect_to movie_reviews_url, notice: 'Review was successfully created.' }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /reviews/1 
    def update
      respond_to do |format|
        if @review.update(review_params)
          format.html { redirect_to movie_reviews_url, notice: 'Review was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /reviews/1
    def destroy
      @review.destroy
  
      respond_to do |format|
        format.html { redirect_to movie_reviews_url, notice: 'Review was successfully destroyed.' }
      end
    end

    def import
        return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
      
        unless params[:file].content_type == 'text/csv'
          return redirect_to request.referer,
                             notice: 'Only CSV files allowed'
        end
        ImportReviewCsv.new(params[:file]).call
        redirect_to request.referer, notice: 'Import started async, please refresh your page after some minutes..'
      end
  
  
    private
  
    def set_review
      @review = @movie.reviews.find(params[:id])
    end
  
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
  
    def review_params
      params.require(:review).permit(:stars, :review, :movie_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesReviewsSys</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
    <% if movie.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
  
        <ul>
          <% movie.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :year %>
      <%= form.number_field :year %>
    </div>
  
    <div class="field">
      <%= form.label :director %>
      <%= form.text_field :director %>
    </div>
  
    <div class="field">
      <%= form.label :actor %>
      <%= form.text_field :actor %>
    </div>
  
    <div class="field">
      <%= form.label :filming_location %>
      <%= form.text_field :filming_location %>
    </div>
  
    <div class="field">
      <%= form.label :country %>
      <%= form.text_field :country %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>
<h4>Search by Actor:</h4>
  <%= search_form_for @q do |f| %>
    <%= f.label :actor_cont %>
    <%= f.search_field :actor_cont %>

    <%= f.submit %>
    <% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Year</th>
      <th>Director</th>
      <th>Actor</th>
      <th>Filming location</th>
      <th>Country</th>
      <th><%= sort_link(@q, :average_rating, "Average rating", default_order: :desc) %></th>
      <th>Reviews</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= movie.year %></td>
        <td><%= movie.director %></td>
        <td><%= movie.actor %></td>
        <td><%= movie.filming_location %></td>
        <td><%= movie.country %></td>
        <td><%= movie.average_rating %></td>
        <td><%= link_to 'Reviews', movie_reviews_path(movie) %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %> | 

<%= form_tag imports_movie_csv_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag '⚙️ Import Movies' %>
<% end %>

<br><br/>

<%= form_tag imports_review_csv_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag '⚙️ Import Reviews' %>
<% end %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @movie.actor %>
</p>

<p>
  <strong>Filming location:</strong>
  <%= @movie.filming_location %>
</p>

<p>
  <strong>Country:</strong>
  <%= @movie.country %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: [:movie , @review]) do |form| %>
    <% if review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
  
        <ul>
          <% review.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :stars %>
      <%= form.number_field :stars %>
    </div>
  
    <div class="field">
      <%= form.label :review %>
      <%= form.text_field :review %>
    </div>
  
    <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', movie_review_url(@review) %> |
<%= link_to 'Back', movie_reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Stars</th>
      <th>Review</th>
      <th>User</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews&.each do |review| %>
      <tr>
        <td><%= review.stars %></td>
        <td><%= review.review %></td>
        <td><%= review.user %></td>
        <td><%= review.movie&.name %></td>
        <td><%= link_to 'Show', movie_review_url(@movie, review) %></td>
        <td><%= link_to 'Edit', edit_movie_review_path(@movie, review) %></td>
        <td><%= link_to 'Destroy', [@movie, review], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_movie_review_path %> | 

<%= link_to 'Movies', movies_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', movie_reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stars:</strong>
  <%= @review.stars %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @review.movie_id %>
</p>

<%= link_to 'Edit', edit_movie_review_path(@review) %> |
<%= link_to 'Back', movie_reviews_path %>